In [1]:
import pandas as pd

In [5]:
structured_logs_df = pd.read_csv('data/mobservice2_stru_my.csv')
structured_logs_df.head()

,Unnamed: 0,LineId,Datetime,Service,Content,EventId,EventTemplate,ParameterList,timestamp
0,0,0,2021-07-01,mobservice2,"2021-07-01 10:54:22,284 | INFO | 0.0.0.4 | 172...",cbed5910,<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobser...,"['2021-07-01', '10:54:22,284', 'c124e30fb40651...",1625136862
1,1,1,2021-07-01,mobservice2,"2021-07-01 10:54:22,297 | INFO | 0.0.0.4 | 172...",645e127b,<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobser...,"['2021-07-01', '10:54:22,297', 'c124e30fb40651...",1625136862
2,2,2,2021-07-01,mobservice2,"2021-07-01 10:54:22,297 | INFO | 0.0.0.4 | 172...",b93239d0,<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobser...,"['2021-07-01', '10:54:22,297', 'c124e30fb40651...",1625136862
3,3,3,2021-07-01,mobservice2,"2021-07-01 10:54:22,404 | INFO | 0.0.0.4 | 172...",6e8ed93a,<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobser...,"['2021-07-01', '10:54:22,404', 'c124e30fb40651...",1625136862
4,4,4,2021-07-01,mobservice2,"2021-07-01 10:54:22,439 | INFO | 0.0.0.4 | 172...",ef8d4b95,<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobser...,"['2021-07-01', '10:54:22,439', 'c124e30fb40651...",1625136862

In [6]:
structured_logs_df = pd.read_csv('data/mobservice2_2021-07-01_2021-07-15.csv')
structured_logs_df.head()

,timestamp,docker_memory_stats_total_pgfault,docker_cpu_core_5_ticks,docker_network_inbound_errors,docker_cpu_core_7_norm_pct,docker_cpu_core_15_norm_pct,docker_diskio_reads,docker_cpu_core_20_pct,docker_cpu_core_6_pct,docker_diskio_summary_ops,...,docker_diskio_read_wait_time,docker_network_outbound_packets,docker_network_outbound_errors,docker_cpu_core_17_pct,docker_cpu_total_pct,docker_cpu_core_9_norm_pct,docker_memory_stats_total_active_file,docker_cpu_core_10_norm_pct,docker_cpu_core_2_norm_pct,docker_memory_stats_total_writeback
0,1.625134e+12,741576.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,0.0,0.000333,0.0,3874816.0,0.0,0.0,0.0
1,1.625134e+12,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,169455.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.625134e+12,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,5088.0,...,8.283904e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.625134e+12,741609.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,0.0,0.084601,0.0,3874816.0,0.0,0.0,0.0
4,1.625134e+12,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,170027.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
templates_df = pd.read_csv('data/mobservice2_temp_my.csv')
templates_df

,Unnamed: 0,EventId,EventTemplate,Occurrences
0,0,cbed5910,<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobser...,666792
1,1,3bab92c3,<*> <*> | INFO | 0.0.0.4 | mobservice2 | mob_h...,61
2,2,645e127b,<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobser...,666779
3,3,c4b2512f,<*> <*> | INFO | 0.0.0.4 | mobservice2 | mob_h...,43
4,4,b93239d0,<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobser...,666765
5,5,6e8ed93a,<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobser...,663416
6,6,ef8d4b95,<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobser...,663346
7,7,fc907e85,<*> <*> | ERROR | 0.0.0.4 | mobservice2 | mob_...,3385
8,8,4124e1a9,<*> <*> | WARNING | 0.0.0.4 | 172.17.0.2 | mob...,7
9,9,401d8aa1,<*> <*> | INFO | 0.0.0.4 | mobservice2 | mob_h...,10
10,10,1e98ef22,<*> <*> | INFO | 0.0.0.4 | mobservice2 | mob_h...,6

In [7]:
templates_df['EventTemplate'].to_list()

['<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobservice2 | <*> | the list of all available services are redisservice1: http://0.0.0.1:9386, redisservice2: http://0.0.0.2:9387',
 "<*> <*> | INFO | 0.0.0.4 | mobservice2 | mob_helper.py -> mob_info_to_redis -> 96 | <*> | request <*> and param={'keys': <*> 'value': <*>",
 '<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobservice2 | <*> | now call <*> <*> as a downstream service',
 '<*> <*> | INFO | 0.0.0.4 | mobservice2 | mob_helper.py -> mob_info_to_redis -> 113 | <*> | info <*> write success',
 "<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobservice2 | <*> | request <*> and param={'keys': <*>",
 "<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobservice2 | <*> | request <*> and param={'keys': <*> 'value': <*>",
 '<*> <*> | INFO | 0.0.0.4 | 172.17.0.2 | mobservice2 | <*> | info <*> write success',
 '<*> <*> | ERROR | 0.0.0.4 | mobservice2 | mob_helper.py -> mob_info_to_redis -> 88 | <*> | <*> information has expired, mobile phone login is invalid',
 '<*> <*> | WARNING | 0.0.0.4 | 172.17.0.2 | mobservice2 | <*> | wait for 11 seconds for follow-up operations to simulate the login failure of the QR code expired',
 '<*> <*> | INFO | 0.0.0.4 | mobservice2 | mob_helper.py -> mob_info_to_redis -> 62 | <*> | now call <*> <*> as a downstream service',
 "<*> <*> | INFO | 0.0.0.4 | mobservice2 | mob_helper.py -> mob_info_to_redis -> 71 | <*> | request <*> and param={'keys': <*>"]

In [7]:
templates_new_df = pd.read_csv('data/mobservice2_temp_my.csv')
templates_new_df

,Unnamed: 0,EventId,EventTemplate,Occurrences
0,0,d7a18fd3,"<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | <*>...",666792
1,1,3e4c17f6,"<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | mob...",61
2,2,5c1c592b,"<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | <*>...",666779
3,3,669fea0d,"<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | mob...",43
4,4,74d7b5f1,"<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | <*>...",666765
5,5,6515bc74,"<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | <*>...",663416
6,6,0df8be0b,"<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | <*>...",663346
7,7,3737b047,"<*>-<*>-<*> <*>:<*>:<*>,<*> | ERROR | <*> | mo...",3385
8,8,5390504c,"<*>-<*>-<*> <*>:<*>:<*>,<*> | WARNING | <*> | ...",7
9,9,7ec341e4,"<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | mob...",10
10,10,fa279958,"<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | mob...",6

In [8]:
templates_new_df['EventTemplate'].to_list()

['<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | <*> | mobservice<*> | <*> | the list of all available services are redisservice<*>: <*> redisservice<*>: <*>',
 "<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | mobservice<*> | mob_helper.py -> mob_info_to_redis -> <*> | <*> | request <*> and param={'keys': <*> 'value': <*>",
 '<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | <*> | mobservice<*> | <*> | now call service:redisservice<*>, inst:<*> as a downstream service',
 '<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | mobservice<*> | mob_helper.py -> mob_info_to_redis -> <*> | <*> | info <*> write success',
 "<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | <*> | mobservice<*> | <*> | request <*> and param={'keys': <*>",
 "<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | <*> | mobservice<*> | <*> | request <*> and param={'keys': <*> 'value': <*>",
 '<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | <*> | mobservice<*> | <*> | info <*> write success',
 '<*>-<*>-<*> <*>:<*>:<*>,<*> | ERROR | <*> | mobservice<*> | mob_helper.py -> mob_info_to_redis -> <*> | <*> | <*> information has expired, mobile phone login is invalid',
 '<*>-<*>-<*> <*>:<*>:<*>,<*> | WARNING | <*> | <*> | mobservice<*> | <*> | wait for <*> seconds for follow-up operations to simulate the login failure of the QR code expired',
 '<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | mobservice<*> | mob_helper.py -> mob_info_to_redis -> <*> | <*> | now call service:redisservice<*>, inst:<*> as a downstream service',
 "<*>-<*>-<*> <*>:<*>:<*>,<*> | INFO | <*> | mobservice<*> | mob_helper.py -> mob_info_to_redis -> <*> | <*> | request <*> and param={'keys': <*>"]

In [ ]:
for idx, row in templates_new_df.iterrows():
    print(row['EventTemplate'])
    print(row['ClusterId'])

target_df = pd.read_csv('data/run_table_2021-07.csv')
print(target_df.shape)

In [6]:
target_df = pd.read_csv(
    "data/run_table_2021-07.csv",
    engine="python",
    on_bad_lines="skip"
)

print(target_df.shape)

(14817, 3)

In [7]:
mobservice2_target_df = target_df[target_df['service'] == 'mobservice2']
print(target_df.shape)
print(mobservice2_target_df.shape)
mobservice2_target_df.head()

(14817, 3)
(6907, 3)

,datetime,service,message
113,2021-07-01,mobservice2,"2021-07-01 15:08:25,556 | WARNING | 0.0.0.4 | ..."
114,2021-07-01,mobservice2,"2021-07-01 15:16:11,833 | WARNING | 0.0.0.4 | ..."
115,2021-07-01,mobservice2,"2021-07-01 15:21:05,900 | WARNING | 0.0.0.4 | ..."
116,2021-07-01,mobservice2,"2021-07-01 15:21:36,455 | WARNING | 0.0.0.4 | ..."
117,2021-07-01,mobservice2,"2021-07-01 15:24:01,962 | WARNING | 0.0.0.4 | ..."